name: git action to Docker Hub
on:
  push:
    branches: [main]

env:
  IMAGE_NAME: amongus-devtools
  TEST_TAG: ${{ secrets.DOCKER_HUB_USERNAME }}/amongus-devtools:test
  RELEASE_TAG: ${{ secrets.DOCKER_HUB_USERNAME }}/amongus-devtools:lastest
  EMAIL: email@email.com

jobs:
  npm-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1-node-dependencies-${{ hashFiles('./package-lock.json') }}
          restore-keys: v1-node-dependencies-
      - name: Install dependencies
        run: npm ci
      - name: Run npm tests
        run: npm test

  snyk-scan:
    needs: npm-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}