name: Update Docker Hub Description
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml
env:
  IMAGE_NAME: amongus-devtools
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        # repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{env.IMAGE_NAME}}
        repository: ${{ github.repository }}
        short-description: ${{ github.event.repository.description }}